"""Create analyzed_strings table

Revision ID: fda6f6a399cf
Revises: 
Create Date: 2025-10-21 14:27:38.554959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fda6f6a399cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyzed_strings',
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('is_palindrome', sa.Boolean(), nullable=False),
    sa.Column('unique_characters', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('character_frequency_map', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('sha256_hash')
    )
    op.create_index(op.f('ix_analyzed_strings_value'), 'analyzed_strings', ['value'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analyzed_strings_value'), table_name='analyzed_strings')
    op.drop_table('analyzed_strings')
    # ### end Alembic commands ###
